# Generated by Django 5.2.17 on 2026-09-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Connexion réussie'), ('login_failed', 'Échec de connexion'), ('logout', 'Déconnexion'), ('otp_requested', 'OTP demandé'), ('otp_success', 'OTP validé'), ('otp_failed', 'Échec OTP'), ('user_created', 'Utilisateur créé'), ('user_updated', 'Utilisateur modifié'), ('role_changed', 'Rôle modifié'), ('permission_changed', 'Permission modifiée'), ('content_created', 'Contenu créé'), ('content_updated', 'Contenu modifié'), ('content_published', 'Contenu publié'), ('content_archived', 'Contenu archivé'), ('content_deleted', 'Contenu supprimé'), ('media_uploaded', 'Média téléversé'), ('media_deleted', 'Média supprimé'), ('document_opened', 'Document ouvert')], db_index=True, max_length=64, verbose_name='action'),
        ),
    ]
